filebeat.inputs:
  - type: filestream
    id: backend-json-logs
    enabled: true
    paths:
      - ../logs/backend.log
    parsers:
      - ndjson:
          add_error_key: true
          message_key: message
    fields:
      service: backend
    fields_under_root: true

  - type: filestream
    id: frontend-json-logs
    enabled: true
    paths:
      - ../logs/frontend.log
    parsers:
      - ndjson:
          add_error_key: true
          message_key: message
    fields:
      service: frontend
    fields_under_root: true

output.logstash:
  hosts: ["localhost:5044"]
